export const PICTURE10_PATH = [
  { name: 'center_101_1.jpg', image: require('../assets/images/pictures/10/center_101_1.jpg'), label: 'center' },
  { name: 'center_101_2.jpg', image: require('../assets/images/pictures/10/center_101_2.jpg'), label: 'center' },
  { name: 'center_104_1.jpg', image: require('../assets/images/pictures/10/center_104_1.jpg'), label: 'center' },
  { name: 'center_110_1.jpg', image: require('../assets/images/pictures/10/center_110_1.jpg'), label: 'center' },
  { name: 'center_110_2.jpg', image: require('../assets/images/pictures/10/center_110_2.jpg'), label: 'center' },
  { name: 'center_110_3.jpg', image: require('../assets/images/pictures/10/center_110_3.jpg'), label: 'center' },
  { name: 'center_110_4.jpg', image: require('../assets/images/pictures/10/center_110_4.jpg'), label: 'center' },
  { name: 'center_110_5.jpg', image: require('../assets/images/pictures/10/center_110_5.jpg'), label: 'center' },
  { name: 'center_113_1.jpg', image: require('../assets/images/pictures/10/center_113_1.jpg'), label: 'center' },
  { name: 'center_113_2.jpg', image: require('../assets/images/pictures/10/center_113_2.jpg'), label: 'center' },
  { name: 'center_113_3.jpg', image: require('../assets/images/pictures/10/center_113_3.jpg'), label: 'center' },
  { name: 'center_116_1.jpg', image: require('../assets/images/pictures/10/center_116_1.jpg'), label: 'center' },
  { name: 'center_116_2.jpg', image: require('../assets/images/pictures/10/center_116_2.jpg'), label: 'center' },
  { name: 'center_116_3.jpg', image: require('../assets/images/pictures/10/center_116_3.jpg'), label: 'center' },
  { name: 'center_119_1.jpg', image: require('../assets/images/pictures/10/center_119_1.jpg'), label: 'center' },
  { name: 'center_122_1.jpg', image: require('../assets/images/pictures/10/center_122_1.jpg'), label: 'center' },
  { name: 'center_122_2.jpg', image: require('../assets/images/pictures/10/center_122_2.jpg'), label: 'center' },
  { name: 'center_122_3.jpg', image: require('../assets/images/pictures/10/center_122_3.jpg'), label: 'center' },
  { name: 'center_122_4.jpg', image: require('../assets/images/pictures/10/center_122_4.jpg'), label: 'center' },
  { name: 'center_125_1.jpg', image: require('../assets/images/pictures/10/center_125_1.jpg'), label: 'center' },
  { name: 'center_125_2.jpg', image: require('../assets/images/pictures/10/center_125_2.jpg'), label: 'center' },
  { name: 'center_128_1.jpg', image: require('../assets/images/pictures/10/center_128_1.jpg'), label: 'center' },
  { name: 'center_128_2.jpg', image: require('../assets/images/pictures/10/center_128_2.jpg'), label: 'center' },
  { name: 'center_128_3.jpg', image: require('../assets/images/pictures/10/center_128_3.jpg'), label: 'center' },
  { name: 'center_131_1.jpg', image: require('../assets/images/pictures/10/center_131_1.jpg'), label: 'center' },
  { name: 'center_131_2.jpg', image: require('../assets/images/pictures/10/center_131_2.jpg'), label: 'center' },
  { name: 'center_131_4.jpg', image: require('../assets/images/pictures/10/center_131_4.jpg'), label: 'center' },
  { name: 'center_134_1.jpg', image: require('../assets/images/pictures/10/center_134_1.jpg'), label: 'center' },
  { name: 'center_137_1.jpg', image: require('../assets/images/pictures/10/center_137_1.jpg'), label: 'center' },
  { name: 'center_140_1.jpg', image: require('../assets/images/pictures/10/center_140_1.jpg'), label: 'center' },
  { name: 'center_140_2.jpg', image: require('../assets/images/pictures/10/center_140_2.jpg'), label: 'center' },
  { name: 'center_143_1.jpg', image: require('../assets/images/pictures/10/center_143_1.jpg'), label: 'center' },
  { name: 'center_143_2.jpg', image: require('../assets/images/pictures/10/center_143_2.jpg'), label: 'center' },
  { name: 'center_143_3.jpg', image: require('../assets/images/pictures/10/center_143_3.jpg'), label: 'center' },
  { name: 'center_143_4.jpg', image: require('../assets/images/pictures/10/center_143_4.jpg'), label: 'center' },
  { name: 'center_146_1.jpg', image: require('../assets/images/pictures/10/center_146_1.jpg'), label: 'center' },
  { name: 'center_152_1.jpg', image: require('../assets/images/pictures/10/center_152_1.jpg'), label: 'center' },
  { name: 'center_152_2.jpg', image: require('../assets/images/pictures/10/center_152_2.jpg'), label: 'center' },
  { name: 'center_158_1.jpg', image: require('../assets/images/pictures/10/center_158_1.jpg'), label: 'center' },
  { name: 'center_161_1.jpg', image: require('../assets/images/pictures/10/center_161_1.jpg'), label: 'center' },
  { name: 'center_164_1.jpg', image: require('../assets/images/pictures/10/center_164_1.jpg'), label: 'center' },
  { name: 'center_170_1.jpg', image: require('../assets/images/pictures/10/center_170_1.jpg'), label: 'center' },
  { name: 'center_170_2.jpg', image: require('../assets/images/pictures/10/center_170_2.jpg'), label: 'center' },
  { name: 'center_74_1.jpg', image: require('../assets/images/pictures/10/center_74_1.jpg'), label: 'center' },
  { name: 'center_83_1.jpg', image: require('../assets/images/pictures/10/center_83_1.jpg'), label: 'center' },
  { name: 'center_83_2.jpg', image: require('../assets/images/pictures/10/center_83_2.jpg'), label: 'center' },
  { name: 'center_92_1.jpg', image: require('../assets/images/pictures/10/center_92_1.jpg'), label: 'center' },
  { name: 'center_92_2.jpg', image: require('../assets/images/pictures/10/center_92_2.jpg'), label: 'center' },
  { name: 'center_92_3.jpg', image: require('../assets/images/pictures/10/center_92_3.jpg'), label: 'center' },
  { name: 'side_101_1.jpg', image: require('../assets/images/pictures/10/side_101_1.jpg'), label: 'side' },
  { name: 'side_122_2.jpg', image: require('../assets/images/pictures/10/side_122_2.jpg'), label: 'side' },
  { name: 'side_140_2.jpg', image: require('../assets/images/pictures/10/side_140_2.jpg'), label: 'side' },
  { name: 'side_158_1.jpg', image: require('../assets/images/pictures/10/side_158_1.jpg'), label: 'side' },
  { name: 'side_173_1.jpg', image: require('../assets/images/pictures/10/side_173_1.jpg'), label: 'side' },
  { name: 'side_104_1.jpg', image: require('../assets/images/pictures/10/side_104_1.jpg'), label: 'side' },
  { name: 'side_122_3.jpg', image: require('../assets/images/pictures/10/side_122_3.jpg'), label: 'side' },
  { name: 'side_143_1.jpg', image: require('../assets/images/pictures/10/side_143_1.jpg'), label: 'side' },
  { name: 'side_158_2.jpg', image: require('../assets/images/pictures/10/side_158_2.jpg'), label: 'side' },
  { name: 'side_197_1.jpg', image: require('../assets/images/pictures/10/side_197_1.jpg'), label: 'side' },
  { name: 'side_104_2.jpg', image: require('../assets/images/pictures/10/side_104_2.jpg'), label: 'side' },
  { name: 'side_125_1.jpg', image: require('../assets/images/pictures/10/side_125_1.jpg'), label: 'side' },
  { name: 'side_146_1.jpg', image: require('../assets/images/pictures/10/side_146_1.jpg'), label: 'side' },
  { name: 'side_158_3.jpg', image: require('../assets/images/pictures/10/side_158_3.jpg'), label: 'side' },
  { name: 'side_65_1.jpg', image: require('../assets/images/pictures/10/side_65_1.jpg'), label: 'side' },
  { name: 'side_107_1.jpg', image: require('../assets/images/pictures/10/side_107_1.jpg'), label: 'side' },
  { name: 'side_128_1.jpg', image: require('../assets/images/pictures/10/side_128_1.jpg'), label: 'side' },
  { name: 'side_146_2.jpg', image: require('../assets/images/pictures/10/side_146_2.jpg'), label: 'side' },
  { name: 'side_161_1.jpg', image: require('../assets/images/pictures/10/side_161_1.jpg'), label: 'side' },
  { name: 'side_80_1.jpg', image: require('../assets/images/pictures/10/side_80_1.jpg'), label: 'side' },
  { name: 'side_107_2.jpg', image: require('../assets/images/pictures/10/side_107_2.jpg'), label: 'side' },
  { name: 'side_128_2.jpg', image: require('../assets/images/pictures/10/side_128_2.jpg'), label: 'side' },
  { name: 'side_146_3.jpg', image: require('../assets/images/pictures/10/side_146_3.jpg'), label: 'side' },
  { name: 'side_161_2.jpg', image: require('../assets/images/pictures/10/side_161_2.jpg'), label: 'side' },
  { name: 'side_83_1.jpg', image: require('../assets/images/pictures/10/side_83_1.jpg'), label: 'side' },
  { name: 'side_110_1.jpg', image: require('../assets/images/pictures/10/side_110_1.jpg'), label: 'side' },
  { name: 'side_131_1.jpg', image: require('../assets/images/pictures/10/side_131_1.jpg'), label: 'side' },
  { name: 'side_146_4.jpg', image: require('../assets/images/pictures/10/side_146_4.jpg'), label: 'side' },
  { name: 'side_164_1.jpg', image: require('../assets/images/pictures/10/side_164_1.jpg'), label: 'side' },
  { name: 'side_89_1.jpg', image: require('../assets/images/pictures/10/side_89_1.jpg'), label: 'side' },
  { name: 'side_113_1.jpg', image: require('../assets/images/pictures/10/side_113_1.jpg'), label: 'side' },
  { name: 'side_134_1.jpg', image: require('../assets/images/pictures/10/side_134_1.jpg'), label: 'side' },
  { name: 'side_149_1.jpg', image: require('../assets/images/pictures/10/side_149_1.jpg'), label: 'side' },
  { name: 'side_167_1.jpg', image: require('../assets/images/pictures/10/side_167_1.jpg'), label: 'side' },
  { name: 'side_98_1.jpg', image: require('../assets/images/pictures/10/side_98_1.jpg'), label: 'side' },
  { name: 'side_98_2.jpg', image: require('../assets/images/pictures/10/side_98_2.jpg'), label: 'side' },
  { name: 'two_107_1.jpg', image: require('../assets/images/pictures/10/two_107_1.jpg'), label: 'two' },
  { name: 'two_122_2.jpg', image: require('../assets/images/pictures/10/two_122_2.jpg'), label: 'two' },
  { name: 'two_131_1.jpg', image: require('../assets/images/pictures/10/two_131_1.jpg'), label: 'two' },
  { name: 'two_143_5.jpg', image: require('../assets/images/pictures/10/two_143_5.jpg'), label: 'two' },
  { name: 'two_155_2.jpg', image: require('../assets/images/pictures/10/two_155_2.jpg'), label: 'two' },
  { name: 'two_110_1.jpg', image: require('../assets/images/pictures/10/two_110_1.jpg'), label: 'two' },
  { name: 'two_125_1.jpg', image: require('../assets/images/pictures/10/two_125_1.jpg'), label: 'two' },
  { name: 'two_131_2.jpg', image: require('../assets/images/pictures/10/two_131_2.jpg'), label: 'two' },
  { name: 'two_143_6.jpg', image: require('../assets/images/pictures/10/two_143_6.jpg'), label: 'two' },
  { name: 'two_158_1.jpg', image: require('../assets/images/pictures/10/two_158_1.jpg'), label: 'two' },
  { name: 'two_113_1.jpg', image: require('../assets/images/pictures/10/two_113_1.jpg'), label: 'two' },
  { name: 'two_125_2.jpg', image: require('../assets/images/pictures/10/two_125_2.jpg'), label: 'two' },
  { name: 'two_137_1.jpg', image: require('../assets/images/pictures/10/two_137_1.jpg'), label: 'two' },
  { name: 'two_143_7.jpg', image: require('../assets/images/pictures/10/two_143_7.jpg'), label: 'two' },
  { name: 'two_167_1.jpg', image: require('../assets/images/pictures/10/two_167_1.jpg'), label: 'two' },
  { name: 'two_113_2.jpg', image: require('../assets/images/pictures/10/two_113_2.jpg'), label: 'two' },
  { name: 'two_125_3.jpg', image: require('../assets/images/pictures/10/two_125_3.jpg'), label: 'two' },
  { name: 'two_137_2.jpg', image: require('../assets/images/pictures/10/two_137_2.jpg'), label: 'two' },
  { name: 'two_146_1.jpg', image: require('../assets/images/pictures/10/two_146_1.jpg'), label: 'two' },
  { name: 'two_167_2.jpg', image: require('../assets/images/pictures/10/two_167_2.jpg'), label: 'two' },
  { name: 'two_113_3.jpg', image: require('../assets/images/pictures/10/two_113_3.jpg'), label: 'two' },
  { name: 'two_125_4.jpg', image: require('../assets/images/pictures/10/two_125_4.jpg'), label: 'two' },
  { name: 'two_137_3.jpg', image: require('../assets/images/pictures/10/two_137_3.jpg'), label: 'two' },
  { name: 'two_146_2.jpg', image: require('../assets/images/pictures/10/two_146_2.jpg'), label: 'two' },
  { name: 'two_173_1.jpg', image: require('../assets/images/pictures/10/two_173_1.jpg'), label: 'two' },
  { name: 'two_116_1.jpg', image: require('../assets/images/pictures/10/two_116_1.jpg'), label: 'two' },
  { name: 'two_125_5.jpg', image: require('../assets/images/pictures/10/two_125_5.jpg'), label: 'two' },
  { name: 'two_140_1.jpg', image: require('../assets/images/pictures/10/two_140_1.jpg'), label: 'two' },
  { name: 'two_149_1.jpg', image: require('../assets/images/pictures/10/two_149_1.jpg'), label: 'two' },
  { name: 'two_173_2.jpg', image: require('../assets/images/pictures/10/two_173_2.jpg'), label: 'two' },
  { name: 'two_116_2.jpg', image: require('../assets/images/pictures/10/two_116_2.jpg'), label: 'two' },
  { name: 'two_125_6.jpg', image: require('../assets/images/pictures/10/two_125_6.jpg'), label: 'two' },
  { name: 'two_143_1.jpg', image: require('../assets/images/pictures/10/two_143_1.jpg'), label: 'two' },
  { name: 'two_152_1.jpg', image: require('../assets/images/pictures/10/two_152_1.jpg'), label: 'two' },
  { name: 'two_86_1.jpg', image: require('../assets/images/pictures/10/two_86_1.jpg'), label: 'two' },
  { name: 'two_116_3.jpg', image: require('../assets/images/pictures/10/two_116_3.jpg'), label: 'two' },
  { name: 'two_128_1.jpg', image: require('../assets/images/pictures/10/two_128_1.jpg'), label: 'two' },
  { name: 'two_143_2.jpg', image: require('../assets/images/pictures/10/two_143_2.jpg'), label: 'two' },
  { name: 'two_152_2.jpg', image: require('../assets/images/pictures/10/two_152_2.jpg'), label: 'two' },
  { name: 'two_92_1.jpg', image: require('../assets/images/pictures/10/two_92_1.jpg'), label: 'two' },
  { name: 'two_95_1.jpg', image: require('../assets/images/pictures/10/two_95_1.jpg'), label: 'two' },
  { name: 'two_98_1.jpg', image: require('../assets/images/pictures/10/two_98_1.jpg'), label: 'two' },
  { name: 'zero_104_1.jpg', image: require('../assets/images/pictures/10/zero_104_1.jpg' ), label: 'zero' },
  { name: 'zero_137_1.jpg', image: require('../assets/images/pictures/10/zero_137_1.jpg' ), label: 'zero' },
  { name: 'zero_152_5.jpg', image: require('../assets/images/pictures/10/zero_152_5.jpg' ), label: 'zero' },
  { name: 'zero_170_2.jpg', image: require('../assets/images/pictures/10/zero_170_2.jpg' ), label: 'zero' },
  { name: 'zero_185_3.jpg', image: require('../assets/images/pictures/10/zero_185_3.jpg' ), label: 'zero' },
  { name: 'zero_122_1.jpg', image: require('../assets/images/pictures/10/zero_122_1.jpg' ), label: 'zero' },
  { name: 'zero_140_1.jpg', image: require('../assets/images/pictures/10/zero_140_1.jpg' ), label: 'zero' },
  { name: 'zero_155_1.jpg', image: require('../assets/images/pictures/10/zero_155_1.jpg' ), label: 'zero' },
  { name: 'zero_173_1.jpg', image: require('../assets/images/pictures/10/zero_173_1.jpg' ), label: 'zero' },
  { name: 'zero_188_1.jpg', image: require('../assets/images/pictures/10/zero_188_1.jpg' ), label: 'zero' },
  { name: 'zero_128_1.jpg', image: require('../assets/images/pictures/10/zero_128_1.jpg' ), label: 'zero' },
  { name: 'zero_146_1.jpg', image: require('../assets/images/pictures/10/zero_146_1.jpg' ), label: 'zero' },
  { name: 'zero_155_2.jpg', image: require('../assets/images/pictures/10/zero_155_2.jpg' ), label: 'zero' },
  { name: 'zero_173_2.jpg', image: require('../assets/images/pictures/10/zero_173_2.jpg' ), label: 'zero' },
  { name: 'zero_191_1.jpg', image: require('../assets/images/pictures/10/zero_191_1.jpg' ), label: 'zero' },
  { name: 'zero_128_2.jpg', image: require('../assets/images/pictures/10/zero_128_2.jpg' ), label: 'zero' },
  { name: 'zero_146_2.jpg', image: require('../assets/images/pictures/10/zero_146_2.jpg' ), label: 'zero' },
  { name: 'zero_155_3.jpg', image: require('../assets/images/pictures/10/zero_155_3.jpg' ), label: 'zero' },
  { name: 'zero_176_1.jpg', image: require('../assets/images/pictures/10/zero_176_1.jpg' ), label: 'zero' },
  { name: 'zero_194_1.jpg', image: require('../assets/images/pictures/10/zero_194_1.jpg' ), label: 'zero' },
  { name: 'zero_134_1.jpg', image: require('../assets/images/pictures/10/zero_134_1.jpg' ), label: 'zero' },
  { name: 'zero_146_3.jpg', image: require('../assets/images/pictures/10/zero_146_3.jpg' ), label: 'zero' },
  { name: 'zero_158_1.jpg', image: require('../assets/images/pictures/10/zero_158_1.jpg' ), label: 'zero' },
  { name: 'zero_179_1.jpg', image: require('../assets/images/pictures/10/zero_179_1.jpg' ), label: 'zero' },
  { name: 'zero_197_1.jpg', image: require('../assets/images/pictures/10/zero_197_1.jpg' ), label: 'zero' },
  { name: 'zero_134_2.jpg', image: require('../assets/images/pictures/10/zero_134_2.jpg' ), label: 'zero' },
  { name: 'zero_146_4.jpg', image: require('../assets/images/pictures/10/zero_146_4.jpg' ), label: 'zero' },
  { name: 'zero_134_3.jpg', image: require('../assets/images/pictures/10/zero_134_3.jpg' ), label: 'zero' },
  { name: 'zero_152_1.jpg', image: require('../assets/images/pictures/10/zero_152_1.jpg' ), label: 'zero' },
  { name: 'zero_164_1.jpg', image: require('../assets/images/pictures/10/zero_164_1.jpg' ), label: 'zero' },
  { name: 'zero_182_1.jpg', image: require('../assets/images/pictures/10/zero_182_1.jpg' ), label: 'zero' },
  { name: 'zero_206_1.jpg', image: require('../assets/images/pictures/10/zero_206_1.jpg' ), label: 'zero' },
  { name: 'zero_134_4.jpg', image: require('../assets/images/pictures/10/zero_134_4.jpg' ), label: 'zero' },
  { name: 'zero_152_2.jpg', image: require('../assets/images/pictures/10/zero_152_2.jpg' ), label: 'zero' },
  { name: 'zero_164_2.jpg', image: require('../assets/images/pictures/10/zero_164_2.jpg' ), label: 'zero' },
  { name: 'zero_182_2.jpg', image: require('../assets/images/pictures/10/zero_182_2.jpg' ), label: 'zero' },
  { name: 'zero_206_2.jpg', image: require('../assets/images/pictures/10/zero_206_2.jpg' ), label: 'zero' },
  { name: 'zero_134_5.jpg', image: require('../assets/images/pictures/10/zero_134_5.jpg' ), label: 'zero' },
  { name: 'zero_152_3.jpg', image: require('../assets/images/pictures/10/zero_152_3.jpg' ), label: 'zero' },
  { name: 'zero_164_3.jpg', image: require('../assets/images/pictures/10/zero_164_3.jpg' ), label: 'zero' },
  { name: 'zero_185_1.jpg', image: require('../assets/images/pictures/10/zero_185_1.jpg' ), label: 'zero' },
  { name: 'zero_224_1.jpg', image: require('../assets/images/pictures/10/zero_224_1.jpg' ), label: 'zero' },
  { name: 'zero_134_6.jpg', image: require('../assets/images/pictures/10/zero_134_6.jpg' ), label: 'zero' },
  { name: 'zero_152_4.jpg', image: require('../assets/images/pictures/10/zero_152_4.jpg' ), label: 'zero' },
  { name: 'zero_170_1.jpg', image: require('../assets/images/pictures/10/zero_170_1.jpg' ), label: 'zero' },
  { name: 'zero_185_2.jpg', image: require('../assets/images/pictures/10/zero_185_2.jpg' ), label: 'zero' },
  { name: 'zero_98_1.jpg', image: require('../assets/images/pictures/10/zero_98_1.jpg' ), label: 'zero' },
  { name: 'zeroside_107_1.jpg', image: require('../assets/images/pictures/10/zeroside_107_1.jpg' ), label: 'zeroside' },
  { name: 'zeroside_107_2.jpg', image: require('../assets/images/pictures/10/zeroside_107_2.jpg' ), label: 'zeroside' },
  { name: 'zeroside_107_3.jpg', image: require('../assets/images/pictures/10/zeroside_107_3.jpg' ), label: 'zeroside' },
  { name: 'zeroside_110_1.jpg', image: require('../assets/images/pictures/10/zeroside_110_1.jpg' ), label: 'zeroside' },
  { name: 'zeroside_110_2.jpg', image: require('../assets/images/pictures/10/zeroside_110_2.jpg' ), label: 'zeroside' },
  { name: 'zeroside_113_1.jpg', image: require('../assets/images/pictures/10/zeroside_113_1.jpg' ), label: 'zeroside' },
  { name: 'zeroside_116_1.jpg', image: require('../assets/images/pictures/10/zeroside_116_1.jpg' ), label: 'zeroside' },
  { name: 'zeroside_116_2.jpg', image: require('../assets/images/pictures/10/zeroside_116_2.jpg' ), label: 'zeroside' },
  { name: 'zeroside_119_1.jpg', image: require('../assets/images/pictures/10/zeroside_119_1.jpg' ), label: 'zeroside' },
  { name: 'zeroside_122_1.jpg', image: require('../assets/images/pictures/10/zeroside_122_1.jpg' ), label: 'zeroside' },
  { name: 'zeroside_122_2.jpg', image: require('../assets/images/pictures/10/zeroside_122_2.jpg' ), label: 'zeroside' },
  { name: 'zeroside_122_3.jpg', image: require('../assets/images/pictures/10/zeroside_122_3.jpg' ), label: 'zeroside' },
  { name: 'zeroside_125_1.jpg', image: require('../assets/images/pictures/10/zeroside_125_1.jpg' ), label: 'zeroside' },
  { name: 'zeroside_125_2.jpg', image: require('../assets/images/pictures/10/zeroside_125_2.jpg' ), label: 'zeroside' },
  { name: 'zeroside_125_3.jpg', image: require('../assets/images/pictures/10/zeroside_125_3.jpg' ), label: 'zeroside' },
  { name: 'zeroside_125_4.jpg', image: require('../assets/images/pictures/10/zeroside_125_4.jpg' ), label: 'zeroside' },
  { name: 'zeroside_128_1.jpg', image: require('../assets/images/pictures/10/zeroside_128_1.jpg' ), label: 'zeroside' },
  { name: 'zeroside_128_2.jpg', image: require('../assets/images/pictures/10/zeroside_128_2.jpg' ), label: 'zeroside' },
  { name: 'zeroside_134_1.jpg', image: require('../assets/images/pictures/10/zeroside_134_1.jpg' ), label: 'zeroside' },
  { name: 'zeroside_134_2.jpg', image: require('../assets/images/pictures/10/zeroside_134_2.jpg' ), label: 'zeroside' },
  { name: 'zeroside_137_1.jpg', image: require('../assets/images/pictures/10/zeroside_137_1.jpg' ), label: 'zeroside' },
  { name: 'zeroside_137_2.jpg', image: require('../assets/images/pictures/10/zeroside_137_2.jpg' ), label: 'zeroside' },
  { name: 'zeroside_140_1.jpg', image: require('../assets/images/pictures/10/zeroside_140_1.jpg' ), label: 'zeroside' },
  { name: 'zeroside_140_2.jpg', image: require('../assets/images/pictures/10/zeroside_140_2.jpg' ), label: 'zeroside' },
  { name: 'zeroside_140_3.jpg', image: require('../assets/images/pictures/10/zeroside_140_3.jpg' ), label: 'zeroside' },
  { name: 'zeroside_143_1.jpg', image: require('../assets/images/pictures/10/zeroside_143_1.jpg' ), label: 'zeroside' },
  { name: 'zeroside_143_2.jpg', image: require('../assets/images/pictures/10/zeroside_143_2.jpg' ), label: 'zeroside' },
  { name: 'zeroside_146_1.jpg', image: require('../assets/images/pictures/10/zeroside_146_1.jpg' ), label: 'zeroside' },
  { name: 'zeroside_146_2.jpg', image: require('../assets/images/pictures/10/zeroside_146_2.jpg' ), label: 'zeroside' },
  { name: 'zeroside_158_1.jpg', image: require('../assets/images/pictures/10/zeroside_158_1.jpg' ), label: 'zeroside' },
  { name: 'zeroside_158_2.jpg', image: require('../assets/images/pictures/10/zeroside_158_2.jpg' ), label: 'zeroside' },
  { name: 'zeroside_161_1.jpg', image: require('../assets/images/pictures/10/zeroside_161_1.jpg' ), label: 'zeroside' },
  { name: 'zeroside_161_2.jpg', image: require('../assets/images/pictures/10/zeroside_161_2.jpg' ), label: 'zeroside' },
  { name: 'zeroside_161_3.jpg', image: require('../assets/images/pictures/10/zeroside_161_3.jpg' ), label: 'zeroside' },
  { name: 'zeroside_164_1.jpg', image: require('../assets/images/pictures/10/zeroside_164_1.jpg' ), label: 'zeroside' },
  { name: 'zeroside_164_2.jpg', image: require('../assets/images/pictures/10/zeroside_164_2.jpg' ), label: 'zeroside' },
  { name: 'zeroside_167_1.jpg', image: require('../assets/images/pictures/10/zeroside_167_1.jpg' ), label: 'zeroside' },
  { name: 'zeroside_167_2.jpg', image: require('../assets/images/pictures/10/zeroside_167_2.jpg' ), label: 'zeroside' },
  { name: 'zeroside_92_1.jpg', image: require('../assets/images/pictures/10/zeroside_92_1.jpg' ), label: 'zeroside' },
  { name: 'zeroside_98_1.jpg', image: require('../assets/images/pictures/10/zeroside_98_1.jpg' ), label: 'zeroside' },
  { name: 'zeroside_98_2.jpg', image: require('../assets/images/pictures/10/zeroside_98_2.jpg' ), label: 'zeroside' },
  ];