export const PICTURE20_PATH = [
    { name: 'center_172_1.jpg', image: require('../assets/images/pictures/20/center_172_1.jpg' ), label: 'center' },
    { name: 'center_175_1.jpg', image: require('../assets/images/pictures/20/center_175_1.jpg' ), label: 'center' },
    { name: 'center_181_1.jpg', image: require('../assets/images/pictures/20/center_181_1.jpg' ), label: 'center' },
    { name: 'center_193_1.jpg', image: require('../assets/images/pictures/20/center_193_1.jpg' ), label: 'center' },
    { name: 'center_202_1.jpg', image: require('../assets/images/pictures/20/center_202_1.jpg' ), label: 'center' },
    { name: 'center_202_2.jpg', image: require('../assets/images/pictures/20/center_202_2.jpg' ), label: 'center' },
    { name: 'center_202_3.jpg', image: require('../assets/images/pictures/20/center_202_3.jpg' ), label: 'center' },
    { name: 'center_208_1.jpg', image: require('../assets/images/pictures/20/center_208_1.jpg' ), label: 'center' },
    { name: 'center_211_1.jpg', image: require('../assets/images/pictures/20/center_211_1.jpg' ), label: 'center' },
    { name: 'center_211_2.jpg', image: require('../assets/images/pictures/20/center_211_2.jpg' ), label: 'center' },
    { name: 'center_217_1.jpg', image: require('../assets/images/pictures/20/center_217_1.jpg' ), label: 'center' },
    { name: 'center_217_2.jpg', image: require('../assets/images/pictures/20/center_217_2.jpg' ), label: 'center' },
    { name: 'center_217_3.jpg', image: require('../assets/images/pictures/20/center_217_3.jpg' ), label: 'center' },
    { name: 'center_220_1.jpg', image: require('../assets/images/pictures/20/center_220_1.jpg' ), label: 'center' },
    { name: 'center_220_2.jpg', image: require('../assets/images/pictures/20/center_220_2.jpg' ), label: 'center' },
    { name: 'center_223_1.jpg', image: require('../assets/images/pictures/20/center_223_1.jpg' ), label: 'center' },
    { name: 'center_226_1.jpg', image: require('../assets/images/pictures/20/center_226_1.jpg' ), label: 'center' },
    { name: 'center_229_1.jpg', image: require('../assets/images/pictures/20/center_229_1.jpg' ), label: 'center' },
    { name: 'center_232_1.jpg', image: require('../assets/images/pictures/20/center_232_1.jpg' ), label: 'center' },
    { name: 'center_232_2.jpg', image: require('../assets/images/pictures/20/center_232_2.jpg' ), label: 'center' },
    { name: 'center_232_3.jpg', image: require('../assets/images/pictures/20/center_232_3.jpg' ), label: 'center' },
    { name: 'center_235_1.jpg', image: require('../assets/images/pictures/20/center_235_1.jpg' ), label: 'center' },
    { name: 'center_235_2.jpg', image: require('../assets/images/pictures/20/center_235_2.jpg' ), label: 'center' },
    { name: 'center_241_1.jpg', image: require('../assets/images/pictures/20/center_241_1.jpg' ), label: 'center' },
    { name: 'center_241_2.jpg', image: require('../assets/images/pictures/20/center_241_2.jpg' ), label: 'center' },
    { name: 'center_241_3.jpg', image: require('../assets/images/pictures/20/center_241_3.jpg' ), label: 'center' },
    { name: 'center_244_1.jpg', image: require('../assets/images/pictures/20/center_244_1.jpg' ), label: 'center' },
    { name: 'center_247_1.jpg', image: require('../assets/images/pictures/20/center_247_1.jpg' ), label: 'center' },
    { name: 'center_247_2.jpg', image: require('../assets/images/pictures/20/center_247_2.jpg' ), label: 'center' },
    { name: 'center_250_1.jpg', image: require('../assets/images/pictures/20/center_250_1.jpg' ), label: 'center' },
    { name: 'center_259_1.jpg', image: require('../assets/images/pictures/20/center_259_1.jpg' ), label: 'center' },
    { name: 'center_259_2.jpg', image: require('../assets/images/pictures/20/center_259_2.jpg' ), label: 'center' },
    { name: 'center_259_3.jpg', image: require('../assets/images/pictures/20/center_259_3.jpg' ), label: 'center' },
    { name: 'center_265_1.jpg', image: require('../assets/images/pictures/20/center_265_1.jpg' ), label: 'center' },
    { name: 'center_268_1.jpg', image: require('../assets/images/pictures/20/center_268_1.jpg' ), label: 'center' },
    { name: 'center_268_2.jpg', image: require('../assets/images/pictures/20/center_268_2.jpg' ), label: 'center' },
    { name: 'center_268_3.jpg', image: require('../assets/images/pictures/20/center_268_3.jpg' ), label: 'center' },
    { name: 'center_271_1.jpg', image: require('../assets/images/pictures/20/center_271_1.jpg' ), label: 'center' },
    { name: 'center_271_2.jpg', image: require('../assets/images/pictures/20/center_271_2.jpg' ), label: 'center' },
    { name: 'center_271_3.jpg', image: require('../assets/images/pictures/20/center_271_3.jpg' ), label: 'center' },
    { name: 'center_271_4.jpg', image: require('../assets/images/pictures/20/center_271_4.jpg' ), label: 'center' },
    { name: 'center_274_1.jpg', image: require('../assets/images/pictures/20/center_274_1.jpg' ), label: 'center' },
    { name: 'center_274_2.jpg', image: require('../assets/images/pictures/20/center_274_2.jpg' ), label: 'center' },
    { name: 'center_283_1.jpg', image: require('../assets/images/pictures/20/center_283_1.jpg' ), label: 'center' },
    { name: 'center_286_1.jpg', image: require('../assets/images/pictures/20/center_286_1.jpg' ), label: 'center' },
    { name: 'center_292_1.jpg', image: require('../assets/images/pictures/20/center_292_1.jpg' ), label: 'center' },
    { name: 'center_295_1.jpg', image: require('../assets/images/pictures/20/center_295_1.jpg' ), label: 'center' },
    { name: 'center_301_1.jpg', image: require('../assets/images/pictures/20/center_301_1.jpg' ), label: 'center' },
    { name: 'center_304_1.jpg', image: require('../assets/images/pictures/20/center_304_1.jpg' ), label: 'center' },
    { name: 'center_319_1.jpg', image: require('../assets/images/pictures/20/center_319_1.jpg' ), label: 'center' },
    { name: 'side_163_1.jpg', image: require('../assets/images/pictures/20/side_163_1.jpg'), label: 'side' },
    { name: 'side_208_1.jpg', image: require('../assets/images/pictures/20/side_208_1.jpg'), label: 'side' },
    { name: 'side_214_1.jpg', image: require('../assets/images/pictures/20/side_214_1.jpg'), label: 'side' },
    { name: 'side_214_2.jpg', image: require('../assets/images/pictures/20/side_214_2.jpg'), label: 'side' },
    { name: 'side_217_1.jpg', image: require('../assets/images/pictures/20/side_217_1.jpg'), label: 'side' },
    { name: 'side_220_1.jpg', image: require('../assets/images/pictures/20/side_220_1.jpg'), label: 'side' },
    { name: 'side_220_2.jpg', image: require('../assets/images/pictures/20/side_220_2.jpg'), label: 'side' },
    { name: 'side_220_3.jpg', image: require('../assets/images/pictures/20/side_220_3.jpg'), label: 'side' },
    { name: 'side_223_1.jpg', image: require('../assets/images/pictures/20/side_223_1.jpg'), label: 'side' },
    { name: 'side_223_2.jpg', image: require('../assets/images/pictures/20/side_223_2.jpg'), label: 'side' },
    { name: 'side_226_1.jpg', image: require('../assets/images/pictures/20/side_226_1.jpg'), label: 'side' },
    { name: 'side_232_1.jpg', image: require('../assets/images/pictures/20/side_232_1.jpg'), label: 'side' },
    { name: 'side_232_2.jpg', image: require('../assets/images/pictures/20/side_232_2.jpg'), label: 'side' },
    { name: 'side_235_1.jpg', image: require('../assets/images/pictures/20/side_235_1.jpg'), label: 'side' },
    { name: 'side_235_2.jpg', image: require('../assets/images/pictures/20/side_235_2.jpg'), label: 'side' },
    { name: 'side_241_1.jpg', image: require('../assets/images/pictures/20/side_241_1.jpg'), label: 'side' },
    { name: 'side_247_1.jpg', image: require('../assets/images/pictures/20/side_247_1.jpg'), label: 'side' },
    { name: 'side_250_1.jpg', image: require('../assets/images/pictures/20/side_250_1.jpg'), label: 'side' },
    { name: 'side_253_1.jpg', image: require('../assets/images/pictures/20/side_253_1.jpg'), label: 'side' },
    { name: 'side_256_1.jpg', image: require('../assets/images/pictures/20/side_256_1.jpg'), label: 'side' },
    { name: 'side_256_2.jpg', image: require('../assets/images/pictures/20/side_256_2.jpg'), label: 'side' },
    { name: 'side_259_1.jpg', image: require('../assets/images/pictures/20/side_259_1.jpg'), label: 'side' },
    { name: 'side_259_2.jpg', image: require('../assets/images/pictures/20/side_259_2.jpg'), label: 'side' },
    { name: 'side_262_1.jpg', image: require('../assets/images/pictures/20/side_262_1.jpg'), label: 'side' },
    { name: 'side_268_1.jpg', image: require('../assets/images/pictures/20/side_268_1.jpg'), label: 'side' },
    { name: 'side_268_2.jpg', image: require('../assets/images/pictures/20/side_268_2.jpg'), label: 'side' },
    { name: 'side_271_1.jpg', image: require('../assets/images/pictures/20/side_271_1.jpg'), label: 'side' },
    { name: 'side_280_1.jpg', image: require('../assets/images/pictures/20/side_280_1.jpg'), label: 'side' },
    { name: 'side_280_2.jpg', image: require('../assets/images/pictures/20/side_280_2.jpg'), label: 'side' },
    { name: 'side_280_3.jpg', image: require('../assets/images/pictures/20/side_280_3.jpg'), label: 'side' },
    { name: 'side_280_4.jpg', image: require('../assets/images/pictures/20/side_280_4.jpg'), label: 'side' },
    { name: 'side_280_5.jpg', image: require('../assets/images/pictures/20/side_280_5.jpg'), label: 'side' },
    { name: 'side_286_1.jpg', image: require('../assets/images/pictures/20/side_286_1.jpg'), label: 'side' },
    { name: 'side_295_1.jpg', image: require('../assets/images/pictures/20/side_295_1.jpg'), label: 'side' },
    { name: 'side_295_2.jpg', image: require('../assets/images/pictures/20/side_295_2.jpg'), label: 'side' },
    { name: 'side_298_1.jpg', image: require('../assets/images/pictures/20/side_298_1.jpg'), label: 'side' },
    { name: 'side_298_2.jpg', image: require('../assets/images/pictures/20/side_298_2.jpg'), label: 'side' },
    { name: 'side_301_1.jpg', image: require('../assets/images/pictures/20/side_301_1.jpg'), label: 'side' },
    { name: 'side_304_1.jpg', image: require('../assets/images/pictures/20/side_304_1.jpg'), label: 'side' },
    { name: 'side_304_2.jpg', image: require('../assets/images/pictures/20/side_304_2.jpg'), label: 'side' },
    { name: 'side_304_3.jpg', image: require('../assets/images/pictures/20/side_304_3.jpg'), label: 'side' },
    { name: 'side_313_1.jpg', image: require('../assets/images/pictures/20/side_313_1.jpg'), label: 'side' },
    { name: 'side_313_2.jpg', image: require('../assets/images/pictures/20/side_313_2.jpg'), label: 'side' },
    { name: 'side_322_1.jpg', image: require('../assets/images/pictures/20/side_322_1.jpg'), label: 'side' },
    { name: 'side_322_2.jpg', image: require('../assets/images/pictures/20/side_322_2.jpg'), label: 'side' },
    { name: 'side_340_1.jpg', image: require('../assets/images/pictures/20/side_340_1.jpg'), label: 'side' },
    { name: 'side_376_1.jpg', image: require('../assets/images/pictures/20/side_376_1.jpg'), label: 'side' },
    { name: 'side_382_1.jpg', image: require('../assets/images/pictures/20/side_382_1.jpg'), label: 'side' },
    { name: 'side_394_1.jpg', image: require('../assets/images/pictures/20/side_394_1.jpg'), label: 'side' },
    { name: 'side_448_1.jpg', image: require('../assets/images/pictures/20/side_448_1.jpg'), label: 'side' },
    { name: 'two_208_1.jpg', image: require('../assets/images/pictures/20/two_208_1.jpg'), label: 'two' },
    { name: 'two_217_1.jpg', image: require('../assets/images/pictures/20/two_217_1.jpg'), label: 'two' },
    { name: 'two_217_2.jpg', image: require('../assets/images/pictures/20/two_217_2.jpg'), label: 'two' },
    { name: 'two_223_1.jpg', image: require('../assets/images/pictures/20/two_223_1.jpg'), label: 'two' },
    { name: 'two_223_2.jpg', image: require('../assets/images/pictures/20/two_223_2.jpg'), label: 'two' },
    { name: 'two_229_1.jpg', image: require('../assets/images/pictures/20/two_229_1.jpg'), label: 'two' },
    { name: 'two_232_1.jpg', image: require('../assets/images/pictures/20/two_232_1.jpg'), label: 'two' },
    { name: 'two_235_1.jpg', image: require('../assets/images/pictures/20/two_235_1.jpg'), label: 'two' },
    { name: 'two_244_1.jpg', image: require('../assets/images/pictures/20/two_244_1.jpg'), label: 'two' },
    { name: 'two_247_1.jpg', image: require('../assets/images/pictures/20/two_247_1.jpg'), label: 'two' },
    { name: 'two_250_1.jpg', image: require('../assets/images/pictures/20/two_250_1.jpg'), label: 'two' },
    { name: 'two_250_2.jpg', image: require('../assets/images/pictures/20/two_250_2.jpg'), label: 'two' },
    { name: 'two_253_1.jpg', image: require('../assets/images/pictures/20/two_253_1.jpg'), label: 'two' },
    { name: 'two_256_1.jpg', image: require('../assets/images/pictures/20/two_256_1.jpg'), label: 'two' },
    { name: 'two_256_2.jpg', image: require('../assets/images/pictures/20/two_256_2.jpg'), label: 'two' },
    { name: 'two_256_3.jpg', image: require('../assets/images/pictures/20/two_256_3.jpg'), label: 'two' },
    { name: 'two_259_1.jpg', image: require('../assets/images/pictures/20/two_259_1.jpg'), label: 'two' },
    { name: 'two_259_2.jpg', image: require('../assets/images/pictures/20/two_259_2.jpg'), label: 'two' },
    { name: 'two_259_3.jpg', image: require('../assets/images/pictures/20/two_259_3.jpg'), label: 'two' },
    { name: 'two_262_1.jpg', image: require('../assets/images/pictures/20/two_262_1.jpg'), label: 'two' },
    { name: 'two_262_2.jpg', image: require('../assets/images/pictures/20/two_262_2.jpg'), label: 'two' },
    { name: 'two_265_1.jpg', image: require('../assets/images/pictures/20/two_265_1.jpg'), label: 'two' },
    { name: 'two_268_1.jpg', image: require('../assets/images/pictures/20/two_268_1.jpg'), label: 'two' },
    { name: 'two_268_2.jpg', image: require('../assets/images/pictures/20/two_268_2.jpg'), label: 'two' },
    { name: 'two_271_1.jpg', image: require('../assets/images/pictures/20/two_271_1.jpg'), label: 'two' },
    { name: 'two_271_2.jpg', image: require('../assets/images/pictures/20/two_271_2.jpg'), label: 'two' },
    { name: 'two_274_1.jpg', image: require('../assets/images/pictures/20/two_274_1.jpg'), label: 'two' },
    { name: 'two_277_1.jpg', image: require('../assets/images/pictures/20/two_277_1.jpg'), label: 'two' },
    { name: 'two_280_1.jpg', image: require('../assets/images/pictures/20/two_280_1.jpg'), label: 'two' },
    { name: 'two_286_1.jpg', image: require('../assets/images/pictures/20/two_286_1.jpg'), label: 'two' },
    { name: 'two_292_1.jpg', image: require('../assets/images/pictures/20/two_292_1.jpg'), label: 'two' },
    { name: 'two_292_2.jpg', image: require('../assets/images/pictures/20/two_292_2.jpg'), label: 'two' },
    { name: 'two_298_1.jpg', image: require('../assets/images/pictures/20/two_298_1.jpg'), label: 'two' },
    { name: 'two_301_1.jpg', image: require('../assets/images/pictures/20/two_301_1.jpg'), label: 'two' },
    { name: 'two_304_1.jpg', image: require('../assets/images/pictures/20/two_304_1.jpg'), label: 'two' },
    { name: 'two_310_1.jpg', image: require('../assets/images/pictures/20/two_310_1.jpg'), label: 'two' },
    { name: 'two_316_1.jpg', image: require('../assets/images/pictures/20/two_316_1.jpg'), label: 'two' },
    { name: 'two_316_2.jpg', image: require('../assets/images/pictures/20/two_316_2.jpg'), label: 'two' },
    { name: 'two_316_3.jpg', image: require('../assets/images/pictures/20/two_316_3.jpg'), label: 'two' },
    { name: 'two_316_4.jpg', image: require('../assets/images/pictures/20/two_316_4.jpg'), label: 'two' },
    { name: 'two_328_1.jpg', image: require('../assets/images/pictures/20/two_328_1.jpg'), label: 'two' },
    { name: 'two_331_1.jpg', image: require('../assets/images/pictures/20/two_331_1.jpg'), label: 'two' },
    { name: 'two_340_1.jpg', image: require('../assets/images/pictures/20/two_340_1.jpg'), label: 'two' },
    { name: 'two_340_2.jpg', image: require('../assets/images/pictures/20/two_340_2.jpg'), label: 'two' },
    { name: 'two_343_1.jpg', image: require('../assets/images/pictures/20/two_343_1.jpg'), label: 'two' },
    { name: 'two_346_1.jpg', image: require('../assets/images/pictures/20/two_346_1.jpg'), label: 'two' },
    { name: 'two_352_1.jpg', image: require('../assets/images/pictures/20/two_352_1.jpg'), label: 'two' },
    { name: 'two_355_1.jpg', image: require('../assets/images/pictures/20/two_355_1.jpg'), label: 'two' },
    { name: 'two_358_1.jpg', image: require('../assets/images/pictures/20/two_358_1.jpg'), label: 'two' },
    { name: 'two_346_1.jpg', image: require('../assets/images/pictures/20/two_346_1.jpg'), label: 'two' },
];